spring.application.name=LMS
spring.datasource.url=jdbc:postgresql://dpg-d7egrkpo3t8c73eecreg-a:5432/laundry_db_rvvf
spring.datasource.username=laundry_db_rvvf_user
spring.datasource.password=oo9IZJTUF6VkE5POiveN3s0sqPHG7bys


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
